version: '3'
services:
    user_service:
        image: 'user_service'
        ports:
            - '8001:8001'
        environment:
            - USER_SERVICE_API=${USER_SERVICE_API}

    user_interaction_service:
        image: 'user_interaction_service'
        ports:
            - '8002:8002'
        environment:
            - USER_INTERACTION_SERVICE_API=${USER_INTERACTION_SERVICE_API}

    content_service:
        image: 'content_service'
        ports:
            - '8000:8000'
        environment:
            - CONTENT_SERVICE_API=${CONTENT_SERVICE_API
