# Generated by Django 4.0.1 on 2022-01-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250)),
                ("story", models.TextField(blank=True)),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
