# Generated by Django 4.0.1 on 2022-01-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_profile_options_remove_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="email",
            new_name="email_id",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
