# Generated by Django 4.0.1 on 2022-01-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_email_profile_email_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email_id",
            field=models.CharField(blank=True, max_length=110, unique=True),
        ),
    ]
