# Generated by Django 4.0.1 on 2022-01-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_profile_email_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email_id",
            field=models.CharField(max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
